####################
# CircleCI configuration reference:
#   https://circleci.com/docs/2.0/configuration-reference
####################
# CircleCI built-in environment variables:
#   https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
####################


####################
# Templates: see "anchors" in https://learnxinyminutes.com/docs/yaml/
####################

# See available image tags at https://hub.docker.com/r/mozilla/sbt/
sbt_image: &sbt_image mozilla/sbt:8u171_1.1.6

# The ~/.sbt directory holds any sbt or Scala versions requested by previous builds.
# The ~/.ivy2 directory holds Java and Scala dependencies declared in the build.
# Caching these two can significantly reduce sbt startup time.
save_cache_settings: &save_cache_settings
  key: telemetry-streaming-{{ .Branch }}-{{ .Environment.CIRCLE_WORKFLOW_ID }}
  paths:
    - ~/.ivy2
    - ~/.sbt

prep_cache_settings: &prep_cache_settings
  name: Clean directories to restore
  command: |
    rm -rf ~/.ivy2 ~/.sbt

restore_cache_settings: &restore_cache_settings
  keys:
    - telemetry-streaming-{{ .Branch }}-{{ .Environment.CIRCLE_WORKFLOW_ID }}
    - telemetry-streaming-{{ .Branch }}
    - telemetry-streaming-

common_settings: &common_settings
  docker:
    - image: *sbt_image
  working_directory: /telemetry-streaming

# CircleCI generally only triggers builds on commits to the main repository,
# so PRs coming from branches of the main repo simply reference builds for existing commits
# (CIRCLE_BRANCH=branchname and CIRCLE_PR_NUMBER is unset);
# The only time PRs will trigger a build is when the PR is referencing a fork
# (CIRCLE_BRANCH=pull/XXX and CIRCLE_PR_NUMBER=XXX).
early_return_for_forked_pull_requests: &early_return_for_forked_pull_requests
  name: Early return if this build is from a forked PR
  command: |
    if [ -n "$CIRCLE_PR_NUMBER" ]; then
      echo "Nothing to upload for forked PRs, so marking this step successful"
      circleci step halt
    fi

early_return_for_skip_tests: &early_return_for_skip_tests
  name: Early return if the latest non-merge commit message contains "[skip-tests]"
  command: |
    COMMIT_MESSAGE=$(git log --format=%B --no-merges -n 1)
    if [[ "$COMMIT_MESSAGE" =~ "[skip-tests]" ]]; then
      echo "Skipping tests due to [skip-tests] flag, so marking this step successful"
      circleci step halt
    fi


####################
# Jobs: see https://circleci.com/docs/2.0/jobs-steps/
####################

version: 2
jobs:

  test:
    <<: *common_settings
    steps:
      - checkout
      - run: *early_return_for_skip_tests
      - run: *prep_cache_settings
      - restore_cache: *restore_cache_settings
      - run:
          name: Run tests that don't rely on Kafka
          command: |
            TEST_OPTIONS='set testOptions in Test := Seq(Tests.Argument("-l", "DockerComposeTag"))'
            sbt "$TEST_OPTIONS" coverage test coverageReport
      - run:
          name: Submit code coverage data
          command: |
            bash <(curl -s https://codecov.io/bash)

  # Instead of using the docker-compose config, we use CircleCI's built-in functionality for
  # spinning up "secondary" docker images and making them available in the same network. See:
  # https://circleci.com/docs/2.0/databases/
  kafka-test:
    <<: *common_settings
    docker:
      - image: *sbt_image
      - image: wurstmeister/zookeeper
      - image: wurstmeister/kafka
        environment:
          - KAFKA_ZOOKEEPER_CONNECT: localhost:2181
          - KAFKA_ADVERTISED_HOST_NAME: localhost
    steps:
      - checkout
      - run: *early_return_for_skip_tests
      - run: *prep_cache_settings
      - restore_cache: *restore_cache_settings
      - run:
          name: Run tests that rely on Kafka
          command: |
            TEST_OPTIONS='set testOptions in Test := Seq(Tests.Argument("-n", "DockerComposeTag"))'
            sbt "$TEST_OPTIONS" coverage test coverageReport
      - run:
          name: Submit code coverage data
          command: |
            bash <(curl -s https://codecov.io/bash)

  lint:
    <<: *common_settings
    steps:
      - checkout
      - run: *early_return_for_skip_tests
      - run: *prep_cache_settings
      - restore_cache: *restore_cache_settings
      - run:
          name: Scalastyle
          command: |
            sbt scalastyle test:scalastyle

  # Assemble an uberjar for the deploy step.
  assembly:
    <<: *common_settings
    steps:
      - run: *early_return_for_forked_pull_requests
      - checkout
      - run:
          name: Assembly
          command: |
            sbt assembly
      - save_cache: *save_cache_settings
      - persist_to_workspace:
          root: target
          paths:
            - scala-2.11/telemetry-streaming-assembly-0.1-SNAPSHOT.jar

  # Uses a "workspace" to get access to the assembled uberjar from the previous stage.
  deploy:
    docker:
      - image: *sbt_image
    working_directory: /telemetry-streaming
    steps:
      - run: *early_return_for_forked_pull_requests
      - checkout
      - attach_workspace:
          at: /telemetry-streaming/target
      - run:
          name: Upload
          command: |
            export JAR=target/scala-2.11/telemetry-streaming-assembly-0.1-SNAPSHOT.jar
            # We pin to a specific commit to avoid unexpected updates to the build code.
            curl -sL https://raw.githubusercontent.com/mozilla/telemetry-batch-view/912adad51f9938c96694edc7de89fe9b6093e7e7/.circleci/deploy.sh | bash


####################
# Workflows: see https://circleci.com/docs/2.0/workflows/
####################

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test
      - kafka-test
      - assembly
      - deploy:
          requires:
            - lint
            - test
            - kafka-test
            - assembly
